### Get all movies
GET http://localhost:8080/movies

### Get movies By Title
GET http://localhost:8080/movies?title=Matrix

### Get movies By Prefix
GET http://localhost:8080/movies/autocomplete?q=Avengers
